# docker-compose.yml
version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/keeptrack
      - /node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING:true
    stdin_open: true
    tty: true
    image: app:react
    container_name: ecommerce-frontend
